#!/usr/bin/env python
print ("    ____ _ __         ")
print ("   / __ \(_)____/ /__ ©")
print ("  / / / / / ___/ //_/ data: Wed/23/15/2022")
print (" / /_/ / (__ ) ,<     V: 1.0 ")
print ("/_____/_/____/_/|_|  Autor: Adriano")
